version: '3.9'

services:
    php-env:
        build: .
        volumes:
            - ./src:/var/www/html
        ports:
            - 9000:80
        depends_on:
            - mysql_db
        networks:
            - mynetwork

    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - mynetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8000:80
        environment:
            PMA_HOST: mysql_db
            PMA_PORT: 3306
        depends_on:
            - mysql_db
        networks:
            - mynetwork

networks:
    mynetwork:
