# Use the official MySQL base image
FROM mysql:latest

# Optionally, set environment variables or configurations for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# Expose the MySQL port (default is 3306)
EXPOSE 3306
